extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  node: true
rules:
  semi: [error, always]
  indent: [error, 4, {SwitchCase: 1}]
